name: Greet Developer

on: [issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: >
          Hi there! ğŸ‘‹ğŸ¼
          As you're new to this repo, I would like to suggest that you read our [code of conduct](https://michaelbrockus.home.blog/code-of-conduct/)
          as well as our [contribution guidelines](https://michaelbrockus.home.blog/contributing/).
          Thanks a bunch for opening your first issue! ğŸ™
        pr-message: >
          Congratulations on opening your first pull request! I well get back to you
          as soon as possible. In the meantime, please make sure you've updated the
          documentation to reflect your changes and have added test automation as
          needed. Thanks! ğŸ™ğŸ¼
